// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;
const SUPABASE_ENABLED = import.meta.env.VITE_SUPABASE_ENABLED === 'true';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a real client only when explicitly enabled and configured,
// otherwise export a no-op shim to avoid runtime errors when disabled.
export const supabase: any = (SUPABASE_ENABLED && SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY)
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : {
      auth: {
        getUser: async () => ({ data: { user: null } }),
      },
      from: () => ({
        insert: async () => ({ error: new Error('Supabase disabled') })
      })
    };